# Generated by Django 5.2.6 on 2026-06-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("preco_atual", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Carteira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="Minha Carteira Principal", max_length=100
                    ),
                ),
                ("margem_de_seguranca_minima", models.FloatField(default=5.0)),
                ("banda_mais", models.FloatField(default=15.0)),
                ("banda_menos", models.FloatField(default=2.5)),
            ],
        ),
        migrations.CreateModel(
            name="AtivoNaCarteira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=0)),
                ("preco_teto", models.FloatField(default=0.0)),
                ("margem_de_seguranca", models.FloatField(default=0.0)),
                (
                    "acao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfolio.acao"
                    ),
                ),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ativos",
                        to="portfolio.carteira",
                    ),
                ),
            ],
        ),
    ]
