# Generated by Django 5.2.6 on 2026-06-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativonacarteira",
            name="margem_de_seguranca",
        ),
    ]
