# Generated by Django 5.2.6 on 2026-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_ativonacarteira_margem_de_seguranca"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativonacarteira",
            name="metodo_valuation",
            field=models.CharField(
                choices=[
                    ("graham", "Benjamin Graham"),
                    ("bazin", "Décio Bazin"),
                    ("lynch", "Peter Lynch"),
                ],
                default="graham",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametro_bazin_dy",
            field=models.FloatField(
                default=6.0, help_text="Dividend Yield Desejado (%) - Apenas para Bazin"
            ),
        ),
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametro_lynch_crescimento",
            field=models.FloatField(
                default=10.0,
                help_text="Taxa de Crescimento (%) - Apenas para Peter Lynch",
            ),
        ),
    ]
