# Generated by Django 5.2.6 on 2026-06-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_ativonacarteira_metodo_valuation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativonacarteira",
            name="metodo_valuation",
            field=models.CharField(
                choices=[
                    ("graham", "Benjamin Graham"),
                    ("bazin", "Décio Bazin"),
                    ("lynch", "Peter Lynch"),
                    ("dfc", "Fluxo de Caixa Descontado (DFC)"),
                    ("projetivo", "Modelo Projetivo"),
                ],
                default="graham",
                max_length=20,
            ),
        ),
    ]
