# Generated by Django 5.2.6 on 2026-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_ativonacarteira_metodo_valuation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametro_dfc_crescimento",
            field=models.FloatField(
                default=5.0, help_text="Crescimento Perpétuo (%) para DFC"
            ),
        ),
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametro_dfc_fluxos",
            field=models.CharField(
                blank=True,
                help_text="Lista de fluxos (ex: [1.5, 1.7])",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametro_dfc_taxa_desconto",
            field=models.FloatField(
                default=10.0, help_text="Taxa de Desconto (%) para DFC"
            ),
        ),
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametro_projetivo_pl_justo",
            field=models.FloatField(
                default=10.0, help_text="P/L Justo para modelo Projetivo"
            ),
        ),
        migrations.AlterField(
            model_name="ativonacarteira",
            name="parametro_bazin_dy",
            field=models.FloatField(
                default=6.0, help_text="Dividend Yield Desejado (%)"
            ),
        ),
        migrations.AlterField(
            model_name="ativonacarteira",
            name="parametro_lynch_crescimento",
            field=models.FloatField(default=10.0, help_text="Taxa de Crescimento (%)"),
        ),
    ]
