# Generated by Django 5.2.6 on 2026-08-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_ativonacarteira_parametro_dfc_crescimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoDolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField(default=5.0, help_text="Cotação USD/BRL")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cripto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("preco_atual_usd", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="ETF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("preco_atual", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="ETFInternacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("preco_atual_usd", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="FII",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "segmento",
                    models.CharField(
                        choices=[
                            ("tijolo", "Tijolo (imóveis físicos)"),
                            ("papel", "Papel (CRI / recebíveis)"),
                            ("hibrido", "Híbrido"),
                            ("fof", "Fundo de Fundos (FOF)"),
                        ],
                        default="tijolo",
                        max_length=10,
                    ),
                ),
                ("preco_atual", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="CriptoNaCarteira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.FloatField(
                        default=0.0, help_text="Permite frações, ex: 0.0053 BTC"
                    ),
                ),
                ("preco_medio_compra_usd", models.FloatField(default=0.0)),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criptos",
                        to="portfolio.carteira",
                    ),
                ),
                (
                    "cripto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.cripto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ETFInternacionalNaCarteira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.FloatField(
                        default=0.0, help_text="Permite frações, ex: 1.35 cotas"
                    ),
                ),
                ("preco_medio_compra_usd", models.FloatField(default=0.0)),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etfs_internacionais",
                        to="portfolio.carteira",
                    ),
                ),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.etfinternacional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ETFNaCarteira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=0)),
                (
                    "preco_teto",
                    models.FloatField(
                        default=0.0,
                        help_text="Opcional — ETFs normalmente não têm 'preço justo'",
                    ),
                ),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etfs_br",
                        to="portfolio.carteira",
                    ),
                ),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfolio.etf"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FIINaCarteira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=0)),
                ("preco_teto", models.FloatField(default=0.0)),
                (
                    "metodo_valuation",
                    models.CharField(
                        choices=[
                            ("bazin", "Décio Bazin (DY desejado)"),
                            ("valor_patrimonial", "Valor Patrimonial (P/VP)"),
                        ],
                        default="bazin",
                        max_length=20,
                    ),
                ),
                (
                    "parametro_bazin_dy",
                    models.FloatField(
                        default=8.0, help_text="Dividend Yield Desejado (%)"
                    ),
                ),
                (
                    "parametro_vp_maximo",
                    models.FloatField(default=1.0, help_text="P/VP máximo aceitável"),
                ),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiis",
                        to="portfolio.carteira",
                    ),
                ),
                (
                    "fii",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfolio.fii"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RendaFixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Ex: CDB Banco XP 2027", max_length=150),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cdb", "CDB"),
                            ("lci", "LCI"),
                            ("lca", "LCA"),
                            ("tesouro_selic", "Tesouro Selic"),
                            ("tesouro_ipca", "Tesouro IPCA+"),
                            ("tesouro_pre", "Tesouro Prefixado"),
                            ("debenture", "Debênture"),
                            ("cri_cra", "CRI/CRA"),
                            ("poupanca", "Poupança"),
                            ("outro", "Outro"),
                        ],
                        default="cdb",
                        max_length=20,
                    ),
                ),
                (
                    "indexador",
                    models.CharField(
                        choices=[
                            ("cdi", "% do CDI"),
                            ("ipca", "IPCA +"),
                            ("selic", "Selic"),
                            ("prefixado", "Prefixado"),
                        ],
                        default="cdi",
                        max_length=15,
                    ),
                ),
                (
                    "taxa_contratada",
                    models.FloatField(
                        default=100.0,
                        help_text="Ex: 110 (110% do CDI) ou 6.0 (IPCA + 6%)",
                    ),
                ),
                ("data_aplicacao", models.DateField(blank=True, null=True)),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                (
                    "valor_aplicado",
                    models.FloatField(
                        default=0.0, help_text="Valor investido originalmente"
                    ),
                ),
                (
                    "valor_atual",
                    models.FloatField(
                        default=0.0,
                        help_text="Valor atualizado — atualize manualmente ou calcule à parte",
                    ),
                ),
                (
                    "isento_ir",
                    models.BooleanField(
                        default=False,
                        help_text="LCI/LCA/CRI/CRA geralmente são isentos de IR para PF",
                    ),
                ),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendas_fixas",
                        to="portfolio.carteira",
                    ),
                ),
            ],
        ),
    ]
