# Generated by Django 5.2.6 on 2026-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_cotacaodolar_cripto_etf_etfinternacional_fii_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativonacarteira",
            name="parametros_especificos",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Guarda parâmetros das formulas específicas (BBAS, PETR, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="ativonacarteira",
            name="metodo_valuation",
            field=models.CharField(
                choices=[
                    ("graham", "Benjamin Graham"),
                    ("bazin", "Décio Bazin"),
                    ("lynch", "Peter Lynch"),
                    ("dfc", "Fluxo de Caixa Descontado (DFC)"),
                    ("projetivo", "Modelo Projetivo"),
                    ("bbas", "Preço Teto BBAS"),
                    ("bbse", "Preço Teto BBSE3"),
                    ("brbi", "Preço Teto BRBI11"),
                    ("flry", "Preço Teto FLRY3"),
                    ("grnd", "Preço Teto GRND3"),
                    ("itsa", "Preço Teto ITSA4"),
                    ("klbn", "Preço Teto KLBN4"),
                    ("petr", "Preço Teto PETR4"),
                    ("sapr", "Preço Teto SAPR4"),
                    ("taee", "Preço Teto TAEE11"),
                    ("vale", "Preço Teto VALE3"),
                    ("wege", "Preço Teto WEGE3"),
                ],
                default="graham",
                max_length=20,
            ),
        ),
    ]
