# Generated by Django 6.1 on 2026-08-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aporte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiarioPlaybook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dados_json",
                    models.JSONField(
                        default=dict, help_text="Guarda todo o state.ativos do frontend"
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "aporte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diario_playbook",
                        to="aporte.aporte",
                    ),
                ),
            ],
        ),
    ]
