// Execute depois de validation/preview.py. Todos os dados de mercado são simulados.
const { chromium } = require('C:/Users/Berna/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path = require('path');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({headless:true, channel:'msedge'});
  try {
    const page = await browser.newPage({viewport:{width:1600,height:1000}});
    const errors=[];
    page.on('pageerror', error=>errors.push(error.message));
    await page.route('https://**/*', route=>route.abort());
    await page.route('http://localhost:8001/**', route=> {
      const url=route.request().url();
      let data;
      if(url.includes('/indices/')) data={data:{ibovespa:{price:132500,percent_change:1.2},sp500:{price:5650,percent_change:-.4},dax:{price:18400,percent_change:.35}}};
      else if(url.includes('/currency/')) data={price:5.12};
      else if(url.includes('/crypto/')) data={data:{BTC:64000,ETH:2800,SOL:145}};
      else if(url.includes('/rates/')) data={data:{TREASURY_10Y:4.21,TREASURY_5Y:3.98}};
      else if(url.includes('/futures/')) data={data:{SP500:5650,NASDAQ:18300,DOW_JONES:40000}};
      else data={data:{ouro:{price:2450,currency:'USD'},prata:{price:29.6,currency:'USD'},petroleo_brent:{price:82,currency:'USD'}}};
      return route.fulfill({json:data,headers:{'Access-Control-Allow-Origin':'*'}});
    });
    await page.goto('http://127.0.0.1:8766/');
    await page.locator('.dashboard-grid').waitFor();
    assert.equal(await page.locator('.sidebar-nav a').filter({hasText:/^\s*Simulador\s*$/}).count(),0);
    const sizes=await page.locator('.dashboard-grid').evaluate(el=>Array.from(el.children).map(c=>c.getBoundingClientRect().width));
    assert(sizes[1]/(sizes[0]+sizes[1])>.39);
    await page.screenshot({path:path.join(__dirname,'aporte-desktop.png'),fullPage:true});
    // Simular e fechar não deve adicionar registros; apenas confirmar grava.
    await page.goto('http://127.0.0.1:8766/aporte/historico/');
    const initialCount=await page.locator('.aporte-card').count();
    await page.goto('http://127.0.0.1:8766/aporte/simulador/');
    await page.locator('[name="valor"]').fill('1500');
    await page.getByRole('button',{name:'Simular Aporte',exact:true}).click();
    await page.getByRole('dialog').waitFor();
    assert.match(await page.getByRole('dialog').innerText(),/Total alocado/);
    await page.screenshot({path:path.join(__dirname,'simulacao-modal-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert(await page.getByRole('dialog').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
    await page.screenshot({path:path.join(__dirname,'simulacao-modal-mobile.png'),fullPage:true});
    await page.getByRole('button',{name:'Não salvar',exact:true}).click();
    assert.equal(await page.locator('dialog[open]').count(),0);
    assert.equal(await page.locator('[name="valor"]').inputValue(),'1500');
    await page.goto('http://127.0.0.1:8766/aporte/historico/');
    assert.equal(await page.locator('.aporte-card').count(),initialCount);
    await page.goto('http://127.0.0.1:8766/aporte/simulador/');
    await page.locator('[name="valor"]').fill('1500');
    await page.getByRole('button',{name:'Simular Aporte',exact:true}).click();
    await page.getByRole('dialog').waitFor();
    await page.getByRole('button',{name:'Salvar aporte',exact:true}).click();
    await page.waitForURL('**/aporte/historico/');
    assert.equal(await page.locator('.aporte-card').count(),initialCount+1);
    await page.setViewportSize({width:1600,height:1000});
    await page.goto('http://127.0.0.1:8766/panorama/');
    await page.waitForFunction(()=>!document.querySelector('#refresh-market').disabled);
    assert.match(await page.locator('#highlight-btc').innerText(),/64\.000/);
    assert.match(await page.locator('#market-rates').innerText(),/Treasury 10 anos/);
    await page.screenshot({path:path.join(__dirname,'panorama-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'Europa',exact:true}).click();
    assert.match(await page.locator('#market-indices').innerText(),/DAX/);
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert(await page.locator('#market-indices').evaluate(el=>el.closest('table').scrollWidth<=el.closest('.table-container').clientWidth));
    await page.screenshot({path:path.join(__dirname,'panorama-mobile.png'),fullPage:true});
    await page.unroute('http://localhost:8001/**');
    await page.route('http://localhost:8001/**',route=>route.fulfill({status:503,json:{detail:'Indisponível'},headers:{'Access-Control-Allow-Origin':'*'}}));
    await page.getByRole('button',{name:'Atualizar panorama'}).click();
    await page.waitForFunction(()=>!document.querySelector('#refresh-market').disabled);
    assert.match(await page.locator('#market-status').innerText(),/indisponíveis/);
    assert.match(await page.locator('#market-currency').innerText(),/Indisponível/);
    assert.equal(await page.locator('#highlight-btc').innerText(),'—');
    await page.goto('http://127.0.0.1:8766/aporte/simulador/');
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.setViewportSize({width:1600,height:1000});
    await page.goto('http://127.0.0.1:8766/playbook/1/');
    const teto=page.locator('[data-field="precoTeto"]');
    assert.equal(await teto.inputValue(),'35.68');
    await teto.fill('35.678');
    await teto.press('Tab');
    assert.equal(await teto.inputValue(),'35.68');
    assert.equal(await page.locator('[data-field="tese"],[data-field="conviccao"],[data-field="falseability"],[data-field="premortem"],[data-field="alternativa"]').count(),0);
    await page.locator('[data-field="vpa"]').fill('20');
    await page.locator('[data-field="lpa"]').fill('3');
    await page.locator('[data-field="gatilho"]').selectOption({index:1});
    await page.locator('[data-field="horizonte"]').selectOption({index:1});
    assert.equal(await page.getByRole('button',{name:'Gerar Prompt',exact:true}).count(),0);
    await page.route('**/playbook/1/analisar/', async route => {
      const response = await route.fetch();
      await new Promise(resolve=>setTimeout(resolve, 1800));
      await route.fulfill({response});
    });
    await page.getByRole('button',{name:'Análise da IA',exact:true}).click();
    await page.locator('#ia-progresso:visible').waitFor();
    assert(await page.getByRole('button',{name:'Salvar Playbook',exact:true}).isDisabled());
    await page.waitForFunction(()=>document.querySelector('#ia-tempo').textContent !== '0s decorridos');
    await page.screenshot({path:path.join(__dirname,'ia-carregando.png'),fullPage:true});
    await page.waitForFunction(()=>document.querySelector('#ia-agente').textContent.includes('GPT'));
    await page.unroute('**/playbook/1/analisar/');
    assert.match(await page.locator('#ia-tentativas').innerText(),/Claude/);
    assert.match(await page.locator('#ia-texto').innerText(),/Análise fictícia/);
    await page.route('**/playbook/1/analisar/', route=>route.fulfill({status:429,json:{
      sucesso:false, codigo:'limites_esgotados', erro:'Todas as IAs configuradas atingiram suas cotas ou limites de uso.',
      tentativas:[{agente:'Kimi',motivo:'cota',mensagem:'Cota indisponível.'}]
    }}));
    await page.getByRole('button',{name:'Análise da IA',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#ia-status').textContent.includes('Todas as IAs'));
    assert.match(await page.locator('#ia-texto').innerText(),/Análise fictícia/);
    await page.unroute('**/playbook/1/analisar/');
    await page.getByRole('button',{name:'Análise da IA',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#ia-status').textContent.includes('concluída'));
    await page.screenshot({path:path.join(__dirname,'playbook-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(__dirname,'playbook-mobile.png'),fullPage:true});
    await page.setViewportSize({width:1600,height:1000});
    await page.getByRole('button',{name:'Salvar análise e Playbook',exact:true}).click();
    await page.waitForURL('**/playbook/');
    await page.goto('http://127.0.0.1:8766/playbook/1/');
    assert.match(await page.locator('#ia-texto').innerText(),/Análise fictícia/);
    assert.match(await page.locator('#ia-status').innerText(),/salva/);
    assert.equal(await teto.inputValue(),'35.68');
    await page.goto('http://127.0.0.1:8766/playbook/');
    page.once('dialog', dialog=>dialog.dismiss());
    await page.locator('form[action="/playbook/1/excluir/"] button').click();
    assert.equal(await page.locator('a[href="/playbook/1/"]').count(),1);
    page.once('dialog', dialog=>dialog.accept());
    await Promise.all([page.waitForURL('**/playbook/'),page.locator('form[action="/playbook/1/excluir/"] button').click()]);
    await page.waitForFunction(()=>!document.querySelector('a[href="/playbook/1/"]'));
    await page.goto('http://127.0.0.1:8766/aporte/historico/');
    await page.locator('form[action="/playbook/1/recriar/"] button').click();
    await page.waitForURL('**/playbook/1/');
    await page.goto('http://127.0.0.1:8766/aporte/historico/');
    page.once('dialog', dialog=>dialog.accept());
    await page.locator('form[action="/aporte/excluir/2/"] button').click();
    await page.waitForFunction(()=>!document.querySelector('form[action="/aporte/excluir/2/"]'));
    assert.equal(errors.length,0,errors.join('\n'));
    console.log('PASS: modal simular/descartar/confirmar, layout desktop/mobile, Panorama com sucesso/falha, Playbook salvar/excluir/recriar, exclusão de aporte.');
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
