# Generated by Django 6.1 on 2026-08-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0007_ativonacarteira_parametros_especificos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_total",
                    models.FloatField(
                        default=0.0, help_text="Valor total simulado ou aportado"
                    ),
                ),
                (
                    "estrategia_utilizada",
                    models.CharField(
                        blank=True,
                        help_text="Ex: concentrado, dividido",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em Análise"),
                            ("cancelado", "Cancelado"),
                            ("efetuado", "Efetuado"),
                        ],
                        default="em_analise",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aportes_historico",
                        to="portfolio.carteira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemAporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(help_text="Ex: PETR4, KNCR11, BTC", max_length=20),
                ),
                (
                    "tipo_ativo",
                    models.CharField(help_text="acao, fii, cripto, etf", max_length=20),
                ),
                (
                    "metodo_valuation",
                    models.CharField(
                        blank=True,
                        help_text="Ex: bazin, graham, bbas",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parametros_valuation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cópia dos parâmetros (P/L, DY, etc) no momento do cálculo",
                    ),
                ),
                ("preco_teto_calculado", models.FloatField(default=0.0)),
                (
                    "preco_atual_momento",
                    models.FloatField(
                        default=0.0, help_text="Preço de mercado no momento do aporte"
                    ),
                ),
                (
                    "valor_aportado",
                    models.FloatField(
                        default=0.0,
                        help_text="Valor financeiro sugerido/destinado a este ativo",
                    ),
                ),
                (
                    "aporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ativos",
                        to="aporte.aporte",
                    ),
                ),
            ],
        ),
    ]
